### ISSUE TITLE
Error when trying to add new action

### ISSUE THREAD

**Issue by wakagashira** [DouglasCAyers/sfdx-mass-action-scheduler#14]
I was following your webinar (Great work btw), and everything was going great till I tried creating the first action ( I.e. Clicking new)

Then I get the error 
"
An internal server error has occurred
Error ID: 26956097-31024 (-1776783716)
D.error()@https://cs68.lightning.force.com/auraFW/javascript/ILuI0gYLCEJeFe3bzJeRPg/aura_prod.js:853:459
init/<()@https://cs68.lightning.force.com/components/one/auraContainer.js:2:93
onXHRReceived()@https://cs68.lightning.force.com/libraries/instrumentation/beaconLib/BeaconLibrary.js:4:323
"
![1-8-2018 5-59-52 pm](https://user-images.githubusercontent.com/35239126/34697020-1f61cf0a-f49f-11e7-96fb-f821fc69e37a.png)

The only thing I can think of is that I have debugging on the sandbox.  But I turned it off and still have the same issue.   

Any idea what I did wrong?   Should I log a ticket with Salesforce?

**Comment by wakagashira** [comment]
Sorry I fat fingered the single signout URL so that was the issue. 
GREAT TOOL!!!!

**Comment by DouglasCAyers** [comment]
Thanks for the update @wakagashira, glad you got it working =)
