### ISSUE TITLE
Error calling Flow

### ISSUE THREAD

**Issue by DouglasCAyers** [DouglasCAyers/sfdx-mass-action-scheduler#15]
Per [Brian](https://douglascayers.com/2017/12/25/mass-action-scheduler/comment-page-1/#comment-3993):

> I’m getting this error, after I already had one successful manual run (adding to campaign automatically just like your video). Ideas?
> 
> Error: System.HttpResponse[Status=Bad Request, StatusCode=400]
[{“actionName”:”Add_to_Current_Month_Collections_Campaign”,”errors”:[{“statusCode”:”UNKNOWN_EXCEPTION”,”message”:”An error occurred when executing a flow interview.”,”fields”:[]}],”isSuccess”:
> 
> Long MessageThe full error message, particularly if more than 255 characters.
Error: System.HttpResponse[Status=Bad Request, StatusCode=400]
[{“actionName”:”Add_to_Current_Month_Collections_Campaign”,”errors”:[{“statusCode”:”UNKNOWN_EXCEPTION”,”message”:”An error occurred when executing a flow interview.”,”fields”:[]}],”isSuccess”:false,”outputValues”:null},{“actionName”:”Add_to_Current_Month_Collections_Campaign”,”errors”:[{“statusCode”:”UNKNOWN_EXCEPTION”,”message”:”An error occurred when executing a flow interview.”,”fields”:[]}],”isSuccess”:false,”outputValues”:null}]
System.HttpRequest[Endpoint=callout:Mass_Action_Scheduler/actions/custom/flow/Add_to_Current_Month_Collections_Campaign, Method=POST]
{
“inputs” : [ {
“SObjectId” : “0033B00000IYgOc”
}, {
“SObjectId” : “0033B00000IYlIW”
} ]
}

**Comment by DouglasCAyers** [comment]
By chance does your Flow or Process Builder do any checking to prevent trying to insert the contact as a CampaignMember twice? Salesforce will only allow a Contact or Lead belong to a campaign once, any attempts to insert a second CampaignMember with same Contact and Campaign IDs will fail.

**Comment by adpa007** [comment]
Hi Doug,
Could you please let me know that is your App Mass Action Scheduler lightning supported or not.

Thanks
Aditya

**Comment by NathalieBlocry** [comment]
I get the exact same error. adding campaign members from a report to a flow in batches of 200. I do check before I create a campaign member to not create duplicates, but I get the error even in empty campaigns. in lightning.
