### ISSUE TITLE
Can't select object?

### ISSUE THREAD

**Issue by annacrotty** [DouglasCAyers/sfdx-mass-action-scheduler#16]
Doug, thank you so much for a great app.  I'm attempting to use for the first time, and I've chosen my action type (Email Alert) but now can't choose an object.  

I saw on a previous issue that this might be related to my Named Credential.  I didn't see any problem there (and was able to login fine after creating it) but did go ahead and wipe the first one and create a new one.  Unfortunately that hasn't made a difference.  

My other pre-requisites seem to have gone smoothly.  My domain seems to be working, and it has definitely been longer than 10 minutes since I created the connected app.

Any ideas about what might be causing this?

**Comment by annacrotty** [comment]
I am reviewing the pre-reqs again, and I do see that I've got 3 Mass Action Schedulers listed in the App Manager.  They're each different "app types" - one is Classic (Managed), one is Lightning (Managed) and one is Connected.  Perhaps I only need one of these?

**Comment by DouglasCAyers** [comment]
Hi @annacrotty,

Regarding the 3 apps, they are all valid. One is the tabs for Classic UI, one is for the tabs for Lightning UI, and one is the actual Connected App for authentication with the Named Credential.

Regarding no objects showing, my first guess was as you noted from what other people reported, needing to re-create their Connected App, Auth. Provider, and Named Credential.

Have you been successful in testing the app with another action type (e.g. Workflow Rules) to confirm the pre-requisites are setup correctly (I really dislike how complicated the initial setup steps are but that's not something I have control over unfortunately).

Thanks

**Comment by annacrotty** [comment]
Thank you!  I did try another action type and had the same issue, so I agree with you, it must be one of the pre-requisites.  I will delete those today and re-create.  

Thanks for creating this app - I have a list of use cases a mile long!

**Comment by annacrotty** [comment]
I'm still struggling, and wondering if I've got the right url here?
https://texastribune.lightning.force.com/services/data/v41.0

**Comment by DouglasCAyers** [comment]
You're very welcome @annacrotty!

That URL is probably the culprit. This is one of those complicated bits I really wish we could get rid of. Check [this article](https://github.com/DouglasCAyers/sfdx-mass-action-scheduler/wiki/Pre-Requisites-Instructions#5-create-named-credential) about creating the URL. It should look like `https://<YourDomain>.my.salesforce.com/services/data/v41.0`. The **lightning.force.com** domain won't work.

And if you're in a sandbox then your URL will look like `https://<YourDomain>.<SandboxInstance>.my.salesforce.com/services/data/v41.0`

**Comment by annacrotty** [comment]
That was it!  Your instructions are absolutely accurate - I was grouping all those bullets as examples for different scenarios, which isn't what they are.  Thank you so much.!

**Comment by DouglasCAyers** [comment]
Great, glad you got it working!
