### ISSUE TITLE
Install Failed 1.5 Sandbox

### ISSUE THREAD

**Issue by bitmite** [DouglasCAyers/sfdx-mass-action-scheduler#17]
Hello, I've stepped through the pre reqs. and that all seems good, but when I try to the install the package on my sandbox via https://test.salesforce.com/packaging/installPackage.apexp?p0=04tf4000001I187 I get the following error, thanks.

Package: Mass Action Scheduler (04tf4000001I187) Error Number: 267749005-5575 (-933433110)
Problem:

1. (Mass_Action_Configuration_Record_Page) Component [force:relatedListSingleContainer] attribute [parentFieldApiName]: The parent record name is invalid.
Mass_Action_Configuration_Record_Page: Component [force:relatedListSingleContainer] attribute [parentFieldApiName]: The parent record name is invalid.

**Comment by DouglasCAyers** [comment]
Hi, this is a known issue with Spring 18. Currently waiting on Salesforce to provide a fix. 

The workaround is to install the unmanaged source code, not as a managed package, if you want to go that route.

**Comment by bitmite** [comment]
Thanks. Looks like it's now Scheduled Spring '18 Patch 7.0. Is there a way to find out when patches are deployed?

**Comment by DouglasCAyers** [comment]
I do not believe we get notifications when patches are deployed, but if you check the "This issue affects me" button on the issue page then you will be notified once that issue is resolved.

**Comment by DouglasCAyers** [comment]
Known issue resolved. I was able to install this package into a Spring 18 sandbox without issue.
