### ISSUE TITLE
Error with Quick Action

### ISSUE THREAD

**Issue by annacrotty** [DouglasCAyers/sfdx-mass-action-scheduler#18]
Hi there,
I set up a mass action (thank you!) and have tried to run it, but have gotten this error:
Error: System.HttpResponse[Status=Bad Request, StatusCode=400]
[{"actionName":"Opportunity.Move_to_Closed_Won","errors":[{"statusCode":"INVALID_TYPE_ON_FIELD_IN_RECORD","message":"Amount: invalid number: $10.00","fields":["Amount"]}],"isSuccess":false,"ou

The quick action being called just moves the stage of the opportunity to closed won.  I did map all the fields in the report.  I'm not quite sure what would be wrong with the fields?

**Comment by DouglasCAyers** [comment]
I think what’s happening here is the literal text “$10.00” is trying to be mapped into the Opportunity.Amount field which expects a number like 10.

Could you provide screen shots of sample data in the source report and of your field mappings?

Thanks

**Comment by annacrotty** [comment]
Absolutely!  I agree with you about the problem, but I'm not sure how to solve it.  The amount column in my report is just the amount on the opportunity - it doesn't need to be changed in this case.

I blurred the donor names, I hope that doesn't cause you a problem!  


![nfg_past_due_pledges___salesforce_-_enterprise_edition](https://user-images.githubusercontent.com/7375753/35450260-4fc76546-0274-11e8-9428-640c3a1c901e.png)
![make_nfg_donations_closed_won___salesforce](https://user-images.githubusercontent.com/7375753/35450264-5211e718-0274-11e8-9065-00ad1a162fd9.png)

Thank you again.

**Comment by DouglasCAyers** [comment]
You indeed found a bug with the amount (currency) field mapping from a report. 

For your specific use case, if your Quick Action is only changing the Stage then perhaps no fields need to be on the Quick Action’s layout and thus no fields needed in the field mapping step thus avoid this bug in the interim. Using pre-defined values in the Quick Action can arbitrarily set the stage value.  Would that work for you?

**Comment by annacrotty** [comment]
Oh duh!  I had not made the connection that  my layout was determining the fields I had to map, even though that should have been obvious to me.  

This completely solved my problem and probably solved other stumbles I was having with similar jobs.  Thank you!

**Comment by DouglasCAyers** [comment]
Glad you got it working! Happy to help :)
