### ISSUE TITLE
No message when try to save with invalid cron expression

### ISSUE THREAD

**Issue by DouglasCAyers** [DouglasCAyers/sfdx-mass-action-scheduler#2]
When trying to save an active configuration with schedule frequency of **Custom** and the cron expression is invalid then no message is displayed to the user indicating what the problem is.

**Comment by DouglasCAyers** [comment]
Fixed in Release 1.4

**Comment by douglascayers** [comment]
![image](https://user-images.githubusercontent.com/4142577/40637862-5efbee56-62cd-11e8-811d-6c7e398b0f58.png)

Any save errors are displayed to the user in an notification alert.
