### ISSUE TITLE
Add Description field to Configurations

### ISSUE THREAD

**Issue by douglascayers** [douglascayers/sfdx-mass-action-scheduler#20]
Per [Eric Schubert](https://success.salesforce.com/0D53A00003Q7i2S),

> When creating a new Mass Action Configuration record, it would be nice to have a field called 'Description'. It can be after the field 'Mass Action Configuration Name' and before the the field 'Source Type'. 
>
> The field 'Mass Action Configuration Name' has a limit of 80 characters, so having a 'Description' field would allow you to put in a sentence or two about what the Mass Action Configuration record is doing.

**Comment by DouglasCAyers** [comment]
Good idea, thanks for the feedback!

**Comment by douglascayers** [comment]
Screen shot of the new description field:

![image](https://user-images.githubusercontent.com/4142577/40638169-32d1ae7c-62cf-11e8-9215-ad1f018df002.png)
