### ISSUE TITLE
Failed test deploying to production

### ISSUE THREAD

**Issue by bruceleestewart** [DouglasCAyers/sfdx-mass-action-scheduler#21]
=== Test Failures [1]
NAME                          METHOD               MESSAGE                                                           STACKTRACE
MA_ReportSourceBatchableTest  test_batchable_fail  System.AssertException: Assertion Failed: Expected: 1, Actual: 0  Class.MA_ReportSourceBatchableTest.test_batchable_fail: line 91, column 1

Is the test anticipating that we make an existing MA_Test_Account_Report report, with at least Account_Id present?  If so - what are the properties of this test report?  Thank you!

[MA_ReportSourceBatchableTest.TXT](https://github.com/DouglasCAyers/sfdx-mass-action-scheduler/files/1712999/MA_ReportSourceBatchableTest.TXT)

**Comment by DouglasCAyers** [comment]
Hi Bruce,

The report and test is expecting exactly one account record to be found. The report filter criteria should be:

Show Me: All Accounts
Created Date: All Time
Filter: Account Name starts with "dca_mass_action: MA Test Account"

Not to discredit your attempts to install the unmanaged code, but any specific reason you aren't installing the managed package? That route would avoid this hassle.

Hope that helps!

**Comment by bruceleestewart** [comment]
Was the managed package the version w/ Sp18 issue?  I tried [Install to Salesforce] right after 1/5 Automation Hour.  I’ll look again tomorrow for managed pkg. thanks, Doug!

**Comment by DouglasCAyers** [comment]
Ahh, gotcha. Yes, installing into Spring 18 orgs **was** a problem but this weekend the known issue has been resolved. That was being tracked in issue #17 

I confirmed you can install the managed package in Spring 18 orgs tonight so you should be good.

**Comment by DouglasCAyers** [comment]
Hi @bruceleestewart, were you able to successfully install the managed package?

**Comment by bruceleestewart** [comment]
Doug - bless you.,
Yes 100%.  I only delayed or avoided it due to the Sp18 issue, and did not know you were rocking out the fix this weekend.  Sorry if I was a pest at all.  This tool is FANTASTIC, esp. in no small part to its ability to bring "batchable" out to the declarative world.  Install worked to prod via managed package; up and running and loving the results!!  Thank you for this amazing tool, and your follow-up!!

**Comment by DouglasCAyers** [comment]
Awesome! You're very welcome, glad it's providing value to you =)
