### ISSUE TITLE
Button on List View

### ISSUE THREAD

**Issue by streetyouth** [douglascayers/sfdx-mass-action-scheduler#23]
Having set everything up, would there be a cool declarative way to make the RUN button (with text of my choice on the button) appear on the list view itself? End users would rather see it there. I've seen it in at least one managed app but I don't know how they managed it.

**Comment by DouglasCAyers** [comment]
To make sure I understand the ask, are you wanting a button on a list view of the records you want to process?

For example, a button on a contacts list view that when clicked it kicked off one of the Mass Action configurations?

The app already comes with an invocable apex class to kick off configurations from flow and process builder via an “apex action”. If you created a list view button that pointed to a flow then your flow could run the Mass Action apex action without you writing any code.

**Comment by DouglasCAyers** [comment]
Hi @streetyouth,

Thanks for using Mass Action Scheduler. I haven't heard back from you in a while, I'm going to close this issue. If you're still interested in discussing this issue please reply and I'll re-open.

Thanks,

Doug

**Comment by bruceleestewart** [comment]
Doug - I think above answers my question - wanting to "invoke" or [Run] a Mass action in another flow.  But what *specifically* is the invocable apex in your package called?

**Comment by streetyouth** [comment]
Hi Doug. I'm Terry Cole, in case the identity isn't clear using my login. I
the time I was hoping to figure out how to add a button to a list view to
cause Mass Action Scheduler to manually trigger. However, I have since
become much better reacquainted with what we can and can't put into the
search layout of list views. I had grown quite rusty on it. I'm not very
sure this is a good idea anymore, even though it seems convenient. It would
be quite wonderful to be able to create buttons or links that are able to
manually trigger some particular Mass Action Scheduler Job. I could imagine
putting them in rich text components or as a utility item or possibly a
global action button. Likely the most direct way to do that with integrity
would be to actually call Mass Action Scheduler from within a flow to run a
particular job.

**Comment by douglascayers** [comment]
@bruceleestewart The apex class name is [MA_RunConfigInvocable](https://github.com/douglascayers/sfdx-mass-action-scheduler/blob/master/force-app/main/default/classes/MA_RunConfigInvocable.cls)

@streetyouth Thanks for the follow up, I've re-opened this feature request. Sounds like you want a way for users to click a button and that would manually trigger one of your Mass Action Configurations.

In the meantime, a way to make this work in Lightning Experience would be to add a Flow component to either a record page or Utility Bar and your Flow have a screen for the user to signal they want to run a configuration. In your Flow, you would use an apex action to run `MA_RunConfigInvocable` labeled **MAS: Run Mass Action**. Your Flow could either hard code the Mass Action Configuration record's ID, or the Flow could use a dynamic choice to give the user an option of which they wanted to run.
