### ISSUE TITLE
Receiving error when trying to choose Action

### ISSUE THREAD

**Issue by ksaner92** [douglascayers/sfdx-mass-action-scheduler#26]
I receive an error message (attached) when on "Choose Action" in creating a new Mass Action record , I also do not show any available processes in the "Action" drop down menu.
![image](https://user-images.githubusercontent.com/36283432/38165666-ada96408-34dc-11e8-9a37-e24eae4ff621.png)

I do have invocable processes setup and active for the object I'm attempting to create a Mass Action for.
The named credential has not changed for our org. I am the user reperesented by the named credential and I do have access to the list view I'm trying to schedule a mass action for.

I have not had any issues like this over the past 4 months I've been using this app. I'm not really sure where to start troubleshooting, could I get some help please?

**Comment by ksaner92** [comment]
Here's the excerpt from the error message in the picture above:

> [Cannot read property 'length' of null]
highlightOptionWithText()@https://primerosystems.lightning.force.com/components/lightning/combobox.js:2:12206
Object.a.runActionOnBufferedTypedCharacters()@https://primerosystems.lightning.force.com/components/lightning-utils.js:2:1181
i()@https://primerosystems.lightning.force.com/components/lightning/combobox.js:2:2963
requestAnimationFrame()@https://primerosystems.lightning.force.com/components/lightning/combobox.js:2:3916

**Comment by ksaner92** [comment]
On the chance I am able to choose an Action, when I proceed to "Field Mappings" I do not have the option to map:
![image](https://user-images.githubusercontent.com/36283432/38198249-9d7c9764-3651-11e8-88c4-613103619c1a.png)

**Comment by ksaner92** [comment]
Solved. Apparently with Spring '18 release, api changed to v42.0. after changing my named credential URL to have v42.0 at the end instead of v41.0, mass scheduler is working for me.

**Comment by ksaner92** [comment]
Nevermind...got ahead of myself, changing the end of my named credential URL did not allow me to successfully choose an action :( Still having issues with this.

**Comment by jnauman** [comment]
I am also experiencing the action selection box not populating. 

"Error calling action "c.getInvocableActions""

**Comment by DouglasCAyers** [comment]
@ksaner92 @jnauman Which version of the app do you all have installed in your orgs? The [current version](https://github.com/DouglasCAyers/sfdx-mass-action-scheduler#packaged-release-history) is 1.5 as of this writing. And you probably do want to update your Named Credential URLs to v42.0.

@ksaner92 so this was working fine for you for 4 months and then one day it stopped working? Any idea what changed in your org that might be related?

Things to double-check are that the Named Credential URL includes your [My Domain](https://github.com/DouglasCAyers/sfdx-mass-action-scheduler/wiki/Pre-Requisites-Instructions#5-create-named-credential) as displayed when in Classic and not what you see in the address bar when in Lightning Experience.

For example, your Named Credential URL should be like https://primerosystems.my.salesforce.com/services/data/v42.0 with a scopes `full` and `refresh_token` and the Callout Option "Generate Authorization Header" checked.

If still get errors, although it's annoying to do, you may want to try re-creating your Connected App, Auth. Provider, and Named Credential from scratch.

**Comment by ksaner92** [comment]
Hi @DouglasCAyers I currently have version 1.5 of the Mass Action Scheduler app installed. I have tried updating my Named Credential URL to v42.0 however that did not change the inability to choose an Action.

And yes, this has been working for me with no hiccups up until 3/29. As annoying as it is when troubleshooting, nothing has changed with my setup or any related objects, list views, process builders.

I do have 2 Named Credentials setup, with the following URLs https://primerosystems.com.my.salesforce.com/services/data/v41.0 and
https://primerosystems.com.my.salesforce.com/services/data/v42.0

Neither are working. I have tried completely uninstalling the app, re-installing, and re-created the Connected App, Auth. Provider, and Named Credentials from scratch 3 times with no success.

![image](https://user-images.githubusercontent.com/36283432/38498689-dd939edc-3bca-11e8-8a9b-e3b1b7086a28.png)

![image](https://user-images.githubusercontent.com/36283432/38498714-f02a87ea-3bca-11e8-86ef-6c6c32c1217f.png)

I appreciate your help!

**Comment by DouglasCAyers** [comment]
Hrmm, that is strange. By chance are you in a sandbox? If yes, then the Named Credential URL will need to be changed to fit the sandbox domain.

**Comment by ksaner92** [comment]
@DouglasCAyers I thought it was pretty strange too :| This is in production. My mass actions in sandbox are still working totally fine.

**Comment by jnauman** [comment]
@DouglasCAyers I went through and re-setup the named credential and everything seems to be working great now! Thanks!

**Comment by DouglasCAyers** [comment]
Good to hear @jnauman

**Comment by jvlaar** [comment]
I'm running into this exact same problem. I am in a sandbox and have made a named credentials with my sandboxes' domain as url. Is there a known cause and/or solution to this problem?

When I visit the url <my domain>.my.salesforce.com/services/data/v42.0 I get 
`<Errors>
<Error>
<errorCode>INVALID_SESSION_ID</errorCode>
<message>Session expired or invalid</message>
</Error>
</Errors>`
Is this related?

**Comment by DouglasCAyers** [comment]
Hi @jvlaar, you won't be able to go to the URL in your browser address bar because the REST API requires an Authorization header with your oauth access token in it. If you are able to create the Named Credential record successfully and get the **Authenticated Status** field to say **Authenticated as you@company.com** and the Named Credential URL is for the same domain as the org you're on, then the only thing I can think of is to make sure the oauth scopes are correct. You need at least `refresh_token` scope, and if you're having issues, probably want to also have `full` scope selected too.

Please share screen shots of your Connected App, Auth. Provider, and Named Credential if you don't mind.

Thanks

**Comment by DouglasCAyers** [comment]
@ksaner92 @jvlaar Do your **Connected App** and **Named Credential** both specify the exact same scopes of `full` and `refresh_token`? Make sure both match exactly and see if that has a difference.

**Comment by DouglasCAyers** [comment]
Another thing to consider per related issue [#7](https://github.com/DouglasCAyers/sfdx-mass-action-scheduler/issues/7#issuecomment-373026969) is check if your production orgs are using Two-Factor Authentication or require High Assurance Session. If **yes**, then you might try to setup your Named Credential to use an integration user that does not require that.

According to another user:
> We also experienced this issue in our Production environment, while the same setup worked fine in our Sandbox. The difference for us was our System Administrator Profile in Production had Session Security Level set to High Assurance and only our corporate Single Sign-On or Two-Factor Authentication were considered High Assurance sessions. The issue was resolved by changing our Named Credentials settings to using a Profile that did not require High Assurance sessions.

**Comment by BethHoward** [comment]
I am also unable to select a Process at the Choose Action step - I just recreated my Connected App, Auth Provider and Named Credential this morning, and I do have a couple of active invocable processes on the object I'm targeting, but no options appear in the picklist. I'm on version 1.5 of the app, am authenticating with a Sys Admin user, and we don't have 2FA enabled. I'm in a sandbox, and I've verified that the Named Credential URL is using the sandbox domain. I'm not sure what else to check in terms of troubleshooting. Any guidance would be appreciated! Thanks!

![tf_connectedapp](https://user-images.githubusercontent.com/11064169/39449980-89b97c04-4c7e-11e8-98e9-3bf8b4bdcca0.png)
![tf_authprovider](https://user-images.githubusercontent.com/11064169/39449985-959cad3e-4c7e-11e8-8f29-07a0f822fab2.png)
![tf_namedcred](https://user-images.githubusercontent.com/11064169/39449997-9e0f8900-4c7e-11e8-8e6a-d846f1f3fccf.png)

**Comment by DouglasCAyers** [comment]
FYI, for the next version of the app I have a new setup page that will automatically create and configure the Connected App, Auth. Provider, and Named Credential for you. I hope this eliminates most of the confusion and trouble with getting Mass Action Scheduler setup for folks.

At the moment, some unrelated apex test classes are failing which prevent me from creating the next package version. I'm waiting on this [known issue](https://success.salesforce.com/issues_view?id=a1p3A000000ATHCQA4) to be fixed. It's currently in progress of being rolled out. Once NA59 gets fixed then I should be able to proceed with providing the next package version.

**Comment by DouglasCAyers** [comment]
Here's a [video sneak peek](https://github.com/DouglasCAyers/sfdx-mass-action-scheduler/raw/7d5e9ecb1fbb6be804a76eb5a99db35bb7b71da2/images/mass-action-auth-setup-video.mp4) of the new auth page. For now, need to download it as .mp4, but I'll post it to YouTube for easier viewing once I release the next version of the app.

**Comment by DouglasCAyers** [comment]
Salesforce is playing a bit of whack-a-mole. The known issue got resolved which fixed my first problem, but in doing so a new problem got introduced and so other previously passing tests are now failing. I'm still working with Salesforce Support on getting all issues fixed so I push out new package updates. Thanks for your patience.
