### ISSUE TITLE
Add New Source Type: SOQL Query

### ISSUE THREAD

**Issue by douglascayers** [douglascayers/sfdx-mass-action-scheduler#3]
Allow users to specify their own custom SOQL query as the data source when a list view or report cannot suffice. For example, to query for users assigned certain permission sets.

Apex nor the REST API provide a "soql query describe", so the most reliable way I can think of for determining which fields are used is to just run the query via REST API and look at the response for the 1st record returned. Disadvantage of this approach is that the query has to be run, so a poor performing query will make the app feel slow when the user is on the field mapping screen.

In Apex, SObject class has a getPopulatedFieldsAsMap() function, but if any field is null in the database then it's not in this map. So, using the REST API is only reliable option here as it will include  field names in the JSON structure even if the value is null.

**Comment by danhowellnz** [comment]
This is a great and very useful idea 👍

**Comment by douglascayers** [comment]
Implemented in Release 2.0 in the develop branch
