### ISSUE TITLE
still unable to complete setup

### ISSUE THREAD

**Issue by ashlynnrs** [DouglasCAyers/sfdx-mass-action-scheduler#30]
I posted some screenshots on closed case #29 (Error message on named credential) because I am still having trouble and have not been able to complete the setup process.

**Comment by ashlynnrs** [comment]
Doug,
I am sorry to keep bothering you. I completed the setup - your suggestion with the callback url solved the issue, and I was able to move through the remaining setup steps and log back in to my sandbox. However, I am not able to see the mass action app from app launcher. Is this an indication that my configuration is still incomplete? Do I need to do something else to make it visible? 

![no app](https://user-images.githubusercontent.com/38735013/39818742-98a7719c-536f-11e8-8b03-dbcc07cc6213.PNG)
![should be there](https://user-images.githubusercontent.com/38735013/39818849-e0899012-536f-11e8-8c0b-97592907ded2.PNG)

**Comment by DouglasCAyers** [comment]
Hi @ashlynnrs, glad you got the authentication working!

The only thing about the apps that I can think of is to ensure your user has the permission set **Mass Action Admin** assigned.

**Comment by ashlynnrs** [comment]
I don’t even have that permission set available to assign. I guess I’m just going to start from scratch again and hope that if I don’t try and fail too many times, the right things will be there in the end.

Ashlynn Sylvain
Data Associate
Friends General Conference
1216 Arch St. #2B
Philadelphia, Pa 19107
(215) 561-1700 x3047
ashlynns@fgcquaker.org<mailto:ashlynns@fgcquaker.org>
www.fgcquaker.org<http://www.fgcquaker.org/>

**Comment by DouglasCAyers** [comment]
Since the Connected App, Auth. Provider, and Named Credential are not dependent on the package, you shouldn't have to redo those. But do try re-installing the Mass Action Scheduler package. On the installation page when it asks who should have access, select Admins Only. See if that gets you any further.

**Comment by ashlynnrs** [comment]
Did that, and now I can access the app ☺ Thanks again, Doug.

Ashlynn Sylvain
Data Associate
Friends General Conference
1216 Arch St. #2B
Philadelphia, Pa 19107
(215) 561-1700 x3047
ashlynns@fgcquaker.org<mailto:ashlynns@fgcquaker.org>
www.fgcquaker.org<http://www.fgcquaker.org/>

**Comment by DouglasCAyers** [comment]
Great!
