### ISSUE TITLE
Not getting any logs

### ISSUE THREAD

**Issue by jmfarber** [douglascayers/sfdx-mass-action-scheduler#36]
I'm setting this up for the first time.  First off, great idea and something that has been very needed for a long time.

What would cause the logs on the mass action record not to generate?  I'm having an issue where the scheduler is failing but I'm not getting any logs.

**Comment by douglascayers** [comment]
Hi @jmfarber, thanks for your interest and feedback on Mass Action Scheduler =)

My only guess is if the batch job itself failed before it could write log records. In Setup, go to Apex Jobs page and see if you see any job failures and their error messages.

Thanks

**Comment by jmfarber** [comment]
I was never able to get process builder to work but I was to get it to call a flow and work.  Two issues:
1. The Logs still didn't generate, not sure if that is the way it's intended or not.
2. The process created two records.  I remember seeing this issues brought by someone else.  The report I'm using only has the master record listed once.  Any idea what would cause it to loop through the report twice?

**Comment by douglascayers** [comment]
1. The Mass Action Log records are only created if errors occur, so if things go fine then there won't be any log records to see on the Mass Action Configuration record.

2. My guess is that the first time the flow fires and causes updates to the record then other triggers, workflow rules, processes, etc. that fire when a record is created or updated fire too, and that one of those has the same logic or firing the same logic that the first flow executed.

**Comment by jmfarber** [comment]
I figured it out.  Hit the button twice!!

**Comment by douglascayers** [comment]
That’ll do it too! Haha
