### ISSUE TITLE
Error passing Boolean into Flow

### ISSUE THREAD

**Issue by jschneider-nexgen** [douglascayers/sfdx-mass-action-scheduler#41]
LEX Summary Report.

`Error: System.HttpResponse[Status=Bad Request, StatusCode=400]
[{"actionName":"Session_Scheduler","errors":[{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varWednesday can't accept values of type String.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varTuesday can't accept values of type String.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varThursday can't accept values of type String.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varSunday can't accept values of type String.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varStartEndDateTime needs to be in this format: YYYY-MM-DDThh:mm:ssZ.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varStartDateTime needs to be in this format: YYYY-MM-DDThh:mm:ssZ.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varSaturday can't accept values of type String.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varMonday can't accept values of type String.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varFriday can't accept values of type String.","fields":[]},{"statusCode":"UNKNOWN_EXCEPTION","message":"The input parameter varEndDate needs to be in this format: YYYY-MM-DD.","fields":[]}],"isSuccess":false,"outputValues":null}]
System.HttpRequest[Endpoint=callout:Mass_Action/actions/custom/flow/Session_Scheduler, Method=POST]
{
"inputs" : [ {
"varWednesday" : "false",
"varTuesday" : "true",
"varThursday" : "false",
"varSunday" : "false",
"varStartEndDateTime" : "9/20/2018 1:00 AM",
"varStartDateTime" : "9/20/2018 9:00 AM",
"varSaturday" : "false",
"varMonday" : "false",
"varFriday" : "false",
"varEndDate" : "10/19/2018",
"varCourse" : "a0j6A000003jS4v"
} ]
}`

![image](https://user-images.githubusercontent.com/23704049/44373108-75f7a580-a4b5-11e8-8807-a986086eb5b5.png)

The days of the week fields are all boolean.  I can reformat the Formula: Last Day Next Month to a Text field with the proper syntax, currently it is a Date field.

**Comment by douglascayers** [comment]
Hi @jschneider-nexgen,

In your report, what data type are the days of the week columns on `Program__c`? Are they text / formula text fields or checkbox / formula checkbox fields?

Unfortunately, the Actions REST API does not let us specify the intended data type of the values being mapped over. So we're left to the system to parse the JSON literal values to Apex data types.

My guess is that in [JSON](https://www.w3schools.com/js/js_json_datatypes.asp), the `boolean` data type is expressed as `true` and `false` without quotes, but the **inputs** array at the end of the error message shows `"true"` and `"false"` within quotes.

You might try using report fields that reference **checkbox** type fields, or modify the inputs to your Flow to accept the String "true" and "false" and route your Decision logic accordingly.

**Comment by jschneider-nexgen** [comment]
They are checkbox (boolean) fields.

**Comment by douglascayers** [comment]
Hi @jschneider-nexgen,  I've opened a new [enhancement](https://github.com/douglascayers/sfdx-mass-action-scheduler/issues/64) request to track checkbox/boolean field support. A few other people have reported similar problems so this new issue will help me track and communicate progress towards it in one central spot. Thanks for your interest in Mass Action Scheduler!
