### ISSUE TITLE
SOLVED: Unable to add Actions

### ISSUE THREAD

**Issue by kat24681012** [douglascayers/sfdx-mass-action-scheduler#46]
Hi-
I had an issue last night in which I wasn't able to add actions.  I used the Automated Setup feature but still had the issue of not being able to see any actions to schedule.

I did find the solution and thought it would be helpful to share my wisdom.

From the app, when you work through the automated setup, there are "Post Setup" instructions (#4).  Pay careful attention to step C:

>  Salesforce will prompt you to log in with the user credentials you want Mass Action Scheduler app to use. On the login page, click Use Custom Domain and enter your org's My Domain.

What I missed is the Use Custom Domain part.  For me, I was just doing a kneejerk click, click, click, username, password, click, carry on.  **The default screen for entering my username and password was the general salesforce login rather than My Domain.  

When I went back and instead chose the custom domain (as the instructions say) it worked perfectly.**

Just pointing this out because it is easy to miss or at least it was for me.  Good Luck.

**Comment by douglascayers** [comment]
Thanks @kat24681012 for the follow up. I'm glad you got it working! I'll leave this issue open in case other folks might stumble upon it and it helps them =)

**Comment by douglascayers** [comment]
Hi @kat24681012, [Release 2.0](https://github.com/douglascayers/sfdx-mass-action-scheduler/wiki/Upgrading-to-Release-2.0) is now available. You can install it from [here](https://github.com/douglascayers/sfdx-mass-action-scheduler#packaged-release-history).

This new release does not require Named Credentials anymore so hopefully the issue you ran into with setting up Mass Action Scheduler the first time won't be a hurdle anymore.

Thanks for your interest in the app and for documenting your findings!
