### ISSUE TITLE
Problem installing Mass Action Scheduler

### ISSUE THREAD

**Issue by kentallman** [douglascayers/sfdx-mass-action-scheduler#48]
Tried to install Mass Action Scheduler in sandbox and got this error:

(Mass_Action_Configuration__c-Mass Action Configuration Layout) The ActionId specified was invalid for ActionType QuickAction. | Mass_Action_Configuration__c-Mass Action Configuration Layout: The ActionId specified was invalid for ActionType QuickAction.
-- | --
(Mass_Action_Log__c-Mass Action Log Layout) The ActionId specified was invalid for ActionType QuickAction. | Mass_Action_Log__c-Mass Action Log Layout: The ActionId specified was invalid for ActionType QuickAction.

**Comment by douglascayers** [comment]
Hi @kentallman, [Release 2.0](https://github.com/douglascayers/sfdx-mass-action-scheduler/wiki/Upgrading-to-Release-2.0) is now available. You can install it from [here](https://github.com/douglascayers/sfdx-mass-action-scheduler#packaged-release-history).

Kindly try out the new version and see if that resolves your issue.

Thanks!

**Comment by kentallman** [comment]
Will do. Thanks Doug.

Ken Tallman
6512 Consulting Group
6512consulting.com<http://6512consulting.com>
970-903-8818

“We make a living by what we get, but we make a life by what we give.”  Winston Churchill


On Jan 2, 2019, at 9:08 AM, Doug Ayers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @kentallman<https://github.com/kentallman>, Release 2.0<https://github.com/douglascayers/sfdx-mass-action-scheduler/wiki/Upgrading-to-Release-2.0> is now available. You can install it from here<https://github.com/douglascayers/sfdx-mass-action-scheduler#packaged-release-history>.

Kindly try out the new version and see if that resolves your issue.

Thanks!
