### ISSUE TITLE
Setup - Edit and Saved Automatically created Named Credential error uri_mismatch

### ISSUE THREAD

**Issue by daveb-501commons** [douglascayers/sfdx-mass-action-scheduler#50]
Have went through the setup before but getting an error on a new instance trying to setup.

Setup Step: Edit the Named Credential and click Save to setup Auth permissions.

Get the following error:
error=redirect_uri_mismatch&error_description=redirect_uri%20must%20match%20configuration

Looking at the Auth Provider that was created the callback is https://login.salesforce.com/services/authcallback/00DA0000000c3NmMAI/Mass_Action which isn't the my domain that is setup.  The my domain URL is what is referenced in the created App and the Named Credential.

**Comment by ChrisGF** [comment]
I am running into the same thing using the automated setup.

**Comment by douglascayers** [comment]
Thanks for reporting this issue. I'll take a look.

To confirm, you all have My Domain enabled in your orgs, correct?

**Comment by daveb-501commons** [comment]
My issue was because I hadn’t deployed the my domain change.  Once deployed everything working good.

**Comment by douglascayers** [comment]
@daveb-501commons thanks for confirming enabling My Domain resolved your issue.

@ChrisGF I'm going to close this issue with resolution being need to enable My Domain. If you have My Domain enabled and still get the issue simply comment back and I'll re-open the issue.

Thanks
