### ISSUE TITLE
Does Mass Action Scheduler support External Objects?

### ISSUE THREAD

**Issue by Clint-Chester** [douglascayers/sfdx-mass-action-scheduler#52]
Hey there :smile: was just wondering whether the Mass Action Scheduler supported reading External Objects? Thanks!

**Comment by douglascayers** [comment]
Hi @Clint-Chester, I don't see why not. I haven't tried personally.

Did you ever try this yourself? Let me know if it doesn't work and I'll re-open this issue to investigate.

Thanks!

**Comment by Clint-Chester** [comment]
Just thought I'd let you know that External Objects do work 😄

**Comment by douglascayers** [comment]
Sweet, thanks for the update
