### ISSUE TITLE
Report record limit?

### ISSUE THREAD

**Issue by jonlarosa** [douglascayers/sfdx-mass-action-scheduler#53]
I'm trying to use the tool to run a WFR against a report that regularly returns about 125K records. In the Apex Jobs list I'm seeing the error "First error: reports:Too many query rows: 50001"

Am I interpreting this correctly to mean that the number of records in a report can't exceed 50K?  Or is it not quite that simple? Is there a limit to the number of records that this will work with?

Thanks,
Jon

**Comment by douglascayers** [comment]
Hi @jonlarosa,

Thanks for your interest in Mass Action Scheduler. The [issue](https://github.com/douglascayers/sfdc-add-campaign-members-by-report/issues/17#issuecomment-332382142) you've hit is not reports themselves but rather a limitation of the REST API, which Mass Action Scheduler is using.

As mentioned [here](https://github.com/douglascayers/sfdx-mass-action-scheduler#data-sources), for more than 10,000 records you'll need to use a List View.

Sorry for the inconvenience, but not much else I can do until Salesforce changes the REST API for reporting, and I don't know when or if that'll happen.

**Comment by jonlarosa** [comment]
Thanks much for your response @douglascayers.
I'm an idiot and didn't RTFM, so I completely missed the part that reports only work for ~10K records. Switched to a list view and I'm sure it will work now but will post back if I run into problems.
Thanks again for your response and for this great tool!

**Comment by douglascayers** [comment]
You’re welcome!
