### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by yuchiehtc** [douglascayers/sfdx-mass-action-scheduler#54]
this is more of a question than issue.

I installed mass action scheduler on our production before, older version and set up a few actions already.  If I want to install the new version (1.6), can I install it without uninstall the existing version?  I hope so, so I won't lose anything that's already there.  please confirm.  Also, do I need to check all the settings again after the installation, "connected app", "auth. provider", and "named credential"?

Thank you
Tina

**Comment by douglascayers** [comment]
Hi @yuchiehtc, thank you for your interest in Mass Action Scheduler =)

When you install the new version, you do not have to re-create the "connected app", "auth. provider", and "named credential". All your existing configurations will still remain and should work the same.

What you may need to do is review and possibly update the page layouts as described here: https://github.com/douglascayers/sfdx-mass-action-scheduler/wiki/Upgrading-to-Release-1.6

As with any app or new features being introduced to an org, always make sure to test first in a sandbox before production.

Thanks
