### ISSUE TITLE
Manual run button

### ISSUE THREAD

**Issue by yuchiehtc** [douglascayers/sfdx-mass-action-scheduler#58]
When I used the older version, I could do manual run.  I installed the new version but don't see the button to manually run any more.  Can you tell me how to add the button?

Thanks

**Comment by douglascayers** [comment]
Hi @yuchiehtc,

You may need to edit the `Mass Action Configuration Layout` page layout for the **Mass Action Configuration** record and add the **Run** action to the "Salesforce Mobile and Lightning Experience Actions" section.

![image](https://user-images.githubusercontent.com/4142577/49625517-73a15480-f99b-11e8-8f62-79d270f57944.png)

**Comment by yuchiehtc** [comment]
got it.  done.  Thank you very much!

**Comment by douglascayers** [comment]
Sure thing!
