### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by JulianJ88** [douglascayers/sfdx-mass-action-scheduler#59]
Hi There! I'm trying to finish installation of MAS. 

I'm on: 

> "b. In Setup, go to the Named Credential record, click Edit, ensure the Start Authentication Flow on Save checkbox is selected, then click Save."
> "c. Salesforce will prompt you to log in with the user credentials you want Mass Action Scheduler app to use. On the login page, click Use Custom Domain and enter nei.my.salesforce.com."

But I'm getting the error:

> We can't authorize you because of an OAuth error. For more information, contact your Salesforce administrator.
> 
> OAUTH_APPROVAL_ERROR_GENERIC : An unexpected error has occured during authentication. Please try again.

I've tried as both named principle and user, and get the same error. 
Any help appreciated. thanks!

**Comment by douglascayers** [comment]
Hi @JulianJ88, I think perhaps the recommendation to enter *nei.my.salesforce.com* for your custom domain was incorrect. On the salesforce login page, when you click the button *Use Custom Domain*, I believe you only need to enter your My Domain prefix. In this case, that's everything before *.my.salesforce.com*, so simply *nei*.

Please try just entering *nei* for the custom domain (or whatever you see in the URL left of .my.salesforce.com).

Sorry for the inconvenience. In the next release that I'm currently working on, there will be *no* need to set up Connected App, Auth. Provider, or Named Credential. My goal (safe harbor) is to have this next version released by end of 2018.

Thanks for your interest in Mass Action Scheduler :)

**Comment by douglascayers** [comment]
Hi @JulianJ88, I'm assuming that the 👍 on my last reply means you were able to move forward with setting up the Named Credential? I'll go ahead and close this issue, but feel free to reply back if you're still having problems authorizing the Named Credential. Thanks
