### ISSUE TITLE
Show full error message in Mass Action Log object

### ISSUE THREAD

**Issue by DouglasCAyers** [DouglasCAyers/sfdx-mass-action-scheduler#8]
Currently the `Mass_Action_Log__c` object has a single `Message__c` field that is TEXT(255). This matches the original design intent of capturing the `AsyncApexJob.ExtendedStatus` field.

However, 255 characters may not be enough information to understand the full error. Try to capture the full exception when batch execution fails.

**Comment by douglascayers** [comment]
![image](https://user-images.githubusercontent.com/4142577/40637781-d685f558-62cc-11e8-8d2f-ae78d06fc3e1.png)

There is now both a short and long error message field.
