### ISSUE TITLE
Clarify which Workflow Rules run when choosing action type

### ISSUE THREAD

**Issue by DouglasCAyers** [DouglasCAyers/sfdx-mass-action-scheduler#9]
Since there are no options to pick a specific workflow rule to run how can I know which ones will try to be run?

**Comment by douglascayers** [comment]
![image](https://user-images.githubusercontent.com/4142577/40637654-d0f6d018-62cb-11e8-858e-780aa881158d.png)

When you choose the action **Workflow Rules**, then the page tells you which rules will run.
